/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import userinterface.StudentRole.CreateNewStudentJPanel;
//import userinterface.StudentRole.CreateNewStudentJPanel;

/**
 *
 * @author Sumeet
 */
public class MainJFrame extends javax.swing.JFrame {

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    EcoSystem system;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    Network network;

    /**
     * Creates new form MainJFrameCopy
     */
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LogiutButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        orangeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1754, 724));

        LeftJPanel.setBackground(new java.awt.Color(51, 51, 51));
        LeftJPanel.setMaximumSize(new java.awt.Dimension(467, 722));
        LeftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/usernameIcon.png"))); // NOI18N
        LeftJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, -1));

        userNameJTextField.setBackground(new java.awt.Color(204, 204, 204));
        userNameJTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        userNameJTextField.setForeground(new java.awt.Color(51, 51, 51));
        LeftJPanel.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 204, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/passwordIcon.png"))); // NOI18N
        LeftJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 347, 40, 41));

        passwordField.setBackground(new java.awt.Color(204, 204, 204));
        passwordField.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        passwordField.setForeground(new java.awt.Color(51, 51, 51));
        passwordField.setText("Password@123");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        LeftJPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 347, 204, 32));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New User? Click on Sign Up");
        LeftJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 204, -1));

        LoginButton.setBackground(new java.awt.Color(51, 204, 255));
        LoginButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Log in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LeftJPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 409, 148, 49));

        RegisterButton.setBackground(new java.awt.Color(51, 204, 255));
        RegisterButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(51, 51, 51));
        RegisterButton.setText("Sign Up");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        LeftJPanel.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 558, 149, 49));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("StudentHub");
        LeftJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 295, 58));

        LogiutButton.setBackground(new java.awt.Color(204, 204, 204));
        LogiutButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        LogiutButton.setForeground(new java.awt.Color(51, 51, 51));
        LogiutButton.setText("Log Out");
        LogiutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogiutButtonActionPerformed(evt);
            }
        });
        LeftJPanel.add(LogiutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 469, 148, 49));

        jSplitPane1.setLeftComponent(LeftJPanel);

        container.setLayout(new java.awt.CardLayout());

        orangeLbl.setBackground(new java.awt.Color(51, 51, 51));
        orangeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/orangesBackground.jpg"))); // NOI18N
        container.add(orangeLbl, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String userName = userNameJTextField.getText();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise enterprise = null;
        Organization organization = null;

        if (userAccount == null) {
            for (Network network : system.getNetworkList()) {
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = e.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = org.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                enterprise = e;
                                organization = org;
                                break;
                            }
                        }
                    } else {
                        enterprise = e;
                        break;
                    }
                    if (organization != null) {
                        break;
                    }
                }
                if (enterprise != null) {
                    break;
                }
            }
        }
        if (userAccount != null && userAccount.getStudent() != null) {
            network = userAccount.getStudent().getNetwork();
        }
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, enterprise, organization, userAccount, system, network));
            layout.next(container);
        }
        LoginButton.setEnabled(false);
        LogiutButton.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
        RegisterButton.setVisible(false);

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LogiutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogiutButtonActionPerformed
        // TODO add your handling code here:
        LogiutButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        LoginButton.setEnabled(true);
        RegisterButton.setVisible(true);
        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        jSplitPane1.setLeftComponent(LeftJPanel);

        container.setLayout(new java.awt.CardLayout());

        orangeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/orangesBackground.jpg")));

        container.add(orangeLbl, "card2");
        jSplitPane1.setRightComponent(container);
        getContentPane().add(jSplitPane1, "card2");
        pack();
        jSplitPane1.setDividerLocation(300);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_LogiutButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed

        System.out.println("user list  " + system.getUserAccountDirectory().getUserAccountList());
        CreateNewStudentJPanel createCus = new CreateNewStudentJPanel(container, system);
        container.add("SignUpJPanel", createCus);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftJPanel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LogiutButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel orangeLbl;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
